apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- audit-client-deployment.yaml
- audit-client-service.yaml
- audit-service-deployment.yaml
- audit-service.yaml
- autopilot-deployment.yaml
- autopilot-service.yaml
- dashboard-deployment.yaml
- dashboard-service.yaml
- datascience-deployment.yaml
- datascience-service.yaml
- gate-deployment.yaml
- gate-service.yaml
- metrixtemplate.yaml
- oes-audit-client-at.yaml
- oes-audit-client-configmap.yaml
- oes-audit-client-preview.yaml
- oes-audit-client-rollout.yaml
- oes-audit-client-stable.yaml
- oes-audit-service-at.yaml
- oes-audit-service-configmap.yaml
- oes-audit-service-preview.yaml
- oes-audit-service-rollout.yaml
- oes-audit-service-stable.yaml
- oes-autopilot-at.yaml
- oes-autopilot-configmap.yaml
- oes-autopilot-preview.yaml
- oes-autopilot-rollout.yaml
- oes-autopilot-stable.yaml
- oes-dashboard-at.yaml
- oes-dashboard-configmap.yaml
- oes-dashboard-preview.yaml
- oes-dashboard-rollout.yaml
- oes-dashboard-stable.yaml
- oes-datascience-at.yaml
- oes-datascience-configmap.yaml
- oes-datascience-preview.yaml
- oes-datascience-rollout.yaml
- oes-datascience-stable.yaml
- oes-gate-at.yaml
- oes-gate-configmap.yaml
- oes-gate-preview.yaml
- oes-gate-rollout.yaml
- oes-gate-stable.yaml
- oes-platform-at.yaml
- oes-platform-configmap.yaml
- oes-platform-preview.yaml
- oes-platform-rollout.yaml
- oes-platform-stable.yaml
- oes-sapor-at.yaml
- oes-sapor-configmap.yaml
- oes-sapor-preview.yaml
- oes-sapor-rollout.yaml
- oes-sapor-stable.yaml
- oes-visibility-at.yaml
- oes-visibility-configmap.yaml
- oes-visibility-preview.yaml
- oes-visibility-rollout.yaml
- oes-visibility-stable.yaml
- opsmx-profile-secret.yaml
- platform-deployment.yaml
- platform-service.yaml
- sapor-deployment.yaml
- sapor-service.yaml
- sayaml-role-rb.yaml
- visibility-deployment.yaml
- visibility-service.yaml
- load-executor-via-jmeter.yaml
- loadbalancer-health.yaml
